"""Add column pokemon_species.is_fake.

Revision ID: 151ab2c50c9
Revises: d68f595546
Create Date: 2013-12-22 19:44:20.079932

"""

# revision identifiers, used by Alembic.
revision = '151ab2c50c9'
down_revision = 'd68f595546'

from alembic import op
import sqlalchemy as sa

def upgrade():
    pokemon_species = sa.sql.table('pokemon_species',
        sa.Column('is_fake', sa.Boolean)
    )

    op.add_column('pokemon_species', sa.Column('is_fake', sa.Boolean()))
    op.execute(pokemon_species.update().values({'is_fake': op.inline_literal(False)}))
    op.alter_column('pokemon_species', 'is_fake', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon_species', 'is_fake')
    ### end Alembic commands ###
