"""Add types.

Revision ID: 16c5acebd14
Revises: d6becece07
Create Date: 2013-11-26 12:13:21.685484

"""

# revision identifiers, used by Alembic.
revision = '16c5acebd14'
down_revision = 'd6becece07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types')
    ### end Alembic commands ###
