"""Add table pokemon_form_moves.

Revision ID: 1711e79741c
Revises: 46131a7d726
Create Date: 2013-12-11 14:39:14.266941

"""

# revision identifiers, used by Alembic.
revision = '1711e79741c'
down_revision = '46131a7d726'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_form_moves',
    sa.Column('pokemon_form_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['pokemon_form_id'], ['pokemon_forms.id'], ),
    sa.PrimaryKeyConstraint('pokemon_form_id', 'move_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_form_moves')
    ### end Alembic commands ###
