"""Add damage classes.

Revision ID: 1998b42d6de
Revises: 38d520d06c8
Create Date: 2013-11-26 13:00:54.129294

"""

# revision identifiers, used by Alembic.
revision = '1998b42d6de'
down_revision = '38d520d06c8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

classes_table = table('damage_classes',
    sa.Column('id', sa.Integer),
    sa.Column('identifier', sa.Unicode),
    sa.Column('name', sa.Unicode)
)

moves_table = table('moves',
    sa.Column('damage_class_id', sa.Integer)
)

def upgrade():
    op.create_table('damage_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )

    op.bulk_insert(classes_table, [
        {'id': 1, 'identifier': 'physical', 'name': 'physical'},
        {'id': 2, 'identifier': 'special', 'name': 'special'},
        {'id': 3, 'identifier': 'non-damaging', 'name': 'non-damaging'}
    ])

    op.add_column('moves', sa.Column('damage_class_id', sa.Integer(),
        sa.ForeignKey('damage_classes.id'), nullable=True))

    op.execute(moves_table.update().values({'damage_class_id': 1}))  # placeholder
    op.alter_column('moves', 'damage_class_id', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'damage_class_id')
    op.drop_table('damage_classes')
    ### end Alembic commands ###
