"""Add Pokémon form types.

Revision ID: 19984d283c2
Revises: 7e21fe9064
Create Date: 2013-12-22 06:54:43.770489

"""

# revision identifiers, used by Alembic.
revision = '19984d283c2'
down_revision = '7e21fe9064'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_form_types',
    sa.Column('pokemon_form_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_form_id'], ['pokemon_forms.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('pokemon_form_id', 'slot')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_form_types')
    ### end Alembic commands ###
