"""Add item categories.

Revision ID: 19dc584f14d
Revises: 3d427da16d9
Create Date: 2014-04-15 13:52:02.146102

"""

# revision identifiers, used by Alembic.
revision = '19dc584f14d'
down_revision = '3d427da16d9'

from alembic import op
import sqlalchemy as sa

item_categories = sa.sql.table('item_categories',
    sa.Column('id', sa.Integer()),
    sa.Column('identifier', sa.Unicode()),
    sa.Column('name', sa.Unicode()),
    sa.Column('order', sa.Integer())
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )

    # Insert a temp row (the real rows will get added when we reload from the CSVs)
    op.bulk_insert(item_categories, [{'id': 1, 'identifier': '', 'name': '', 'order': 1}])
    op.add_column('items', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('item_category_id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('items', 'item_category_id', server_default=None)


def downgrade():
    op.drop_column('items', 'item_category_id')
    op.drop_column('items', 'order')
    op.drop_table('item_categories')
