"""keep track of held items on the trainer_items side

Revision ID: 1acb40578ac
Revises: 17bdce9d660
Create Date: 2013-09-28 19:42:53.394351

"""

# revision identifiers, used by Alembic.
revision = '1acb40578ac'
down_revision = '17bdce9d660'

from alembic import op
import sqlalchemy as sqla
from sqlalchemy.sql import column, select, table

Pokemon = table('pokemon',
    column('id', sqla.Integer),
    column('held_item_id', sqla.Integer)
)

TrainerItem = table('trainer_items',
    column('id', sqla.Integer),
    column('pokemon_id', sqla.Integer)
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_items', sqla.Column('pokemon_id', sqla.Integer(), nullable=True))
    subquery = select([Pokemon.c.id]).where(Pokemon.c.held_item_id == TrainerItem.c.id)
    op.execute(TrainerItem.update().values({'pokemon_id': subquery}))
    op.drop_column('pokemon', 'held_item_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sqla.Column('held_item_id', sqla.INTEGER(), nullable=True))
    subquery = select([TrainerItem.c.id]).where(TrainerItem.c.pokemon_id == Pokemon.c.id)
    op.execute(TrainerItem.update().values({'trainer_item_id': subquery}))
    op.drop_column('trainer_items', 'pokemon_id')
    ### end Alembic commands ###
