"""Add Pokémon species genders.

Revision ID: 2b1cbfad9c4
Revises: 43f39d0d550
Create Date: 2013-12-21 07:00:21.175426

"""

# revision identifiers, used by Alembic.
revision = '2b1cbfad9c4'
down_revision = '43f39d0d550'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_species_genders',
    sa.Column('pokemon_species_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['pokemon_species_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('pokemon_species_id', 'gender_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_species_genders')
    ### end Alembic commands ###
