"""Add column trainers.email.

Revision ID: 2df1183d7
Revises: 15ac6dc43be
Create Date: 2014-07-06 14:34:37.074147

"""

# revision identifiers, used by Alembic.
revision = '2df1183d7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('email', sa.Unicode(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'email')
    ### end Alembic commands ###
