"""Add column rarity.price.

Revision ID: 36e5adfc58
Revises: 1711e79741c
Create Date: 2013-12-12 00:38:42.845945

"""

# revision identifiers, used by Alembic.
revision = '36e5adfc58'
down_revision = '1711e79741c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


def upgrade():
    rarities = table('rarities',
        sa.Column('price', sa.Integer)
    )

    op.add_column('rarities', sa.Column('price', sa.Integer()))
    op.execute(rarities.update().values({'price': op.inline_literal(0)}))
    op.alter_column('rarities', 'price', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rarities', 'price')
    ### end Alembic commands ###
