"""Add moves.

Revision ID: 38d520d06c8
Revises: 16c5acebd14
Create Date: 2013-11-26 12:47:11.925850

"""

# revision identifiers, used by Alembic.
revision = '38d520d06c8'
down_revision = '16c5acebd14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('target', sa.Unicode(), nullable=False),
    sa.Column('category', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    ### end Alembic commands ###
