"""Add column pokemon_species.forms_are_squashable.

Revision ID: 3e91c95c5c1
Revises: 151ab2c50c9
Create Date: 2013-12-22 21:18:27.836807

"""

# revision identifiers, used by Alembic.
revision = '3e91c95c5c1'
down_revision = '151ab2c50c9'

from alembic import op
import sqlalchemy as sa

def upgrade():
    pokemon_species = sa.sql.table('pokemon_species',
        sa.Column('forms_are_squashable', sa.Boolean)
    )

    op.add_column('pokemon_species', sa.Column('forms_are_squashable', sa.Boolean()))
    op.execute(pokemon_species.update().values({'forms_are_squashable': op.inline_literal(False)}))
    op.alter_column('pokemon_species', 'forms_are_squashable', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon_species', 'forms_are_squashable')
    ### end Alembic commands ###
