"""Add password reset requests.

Revision ID: 42a62c35cae
Revises: 40812ed2617
Create Date: 2015-03-19 21:37:50.888409

"""

# revision identifiers, used by Alembic.
revision = '42a62c35cae'
down_revision = '40812ed2617'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_requests',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('token', sa.Unicode(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('trainer_id', 'timestamp'),
    sa.UniqueConstraint('token')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_requests')
    ### end Alembic commands ###
