"""Add more battle stuff.

Revision ID: 4d5e6e65a81
Revises: 400f800ea13
Create Date: 2014-08-27 14:26:12.831664

"""

# revision identifiers, used by Alembic.
revision = '4d5e6e65a81'
down_revision = '400f800ea13'

from alembic import op
import sqlalchemy as sa

battle_outcomes = sa.sql.table(
    'battle_outcomes',
    sa.Column('identifier', sa.Unicode)
)

battle_lengths = sa.sql.table(
    'battle_lengths',
    sa.Column('identifier', sa.Unicode)
)

def upgrade():
    # Add battle_outcomes
    op.create_table(
        'battle_outcomes',
        sa.Column('identifier', sa.Unicode(), nullable=False),
        sa.PrimaryKeyConstraint('identifier')
    )

    op.bulk_insert(battle_outcomes, [
        {'identifier': 'win'},
        {'identifier': 'loss'},
        {'identifier': 'draw'}
    ])

    # Add battle_lengths
    op.create_table(
        'battle_lengths',
        sa.Column('identifier', sa.Unicode(), nullable=False),
        sa.PrimaryKeyConstraint('identifier')
    )

    op.bulk_insert(battle_lengths, [
        {'identifier': 'full'},
        {'identifier': 'short'},
        {'identifier': 'dq'},
        {'identifier': 'cancelled'}
    ])

    # Add new columns to stuff
    op.add_column('battle_pokemon',
        sa.Column('kos', sa.Integer(), nullable=True))

    op.alter_column('battle_pokemon', 'gender_id', nullable=False,
        existing_type=sa.Integer)

    op.add_column('battle_teams',
        sa.Column('outcome', sa.Unicode(), nullable=True))

    # Battles aren't actually closeable yet so I'm not going to bother carrying
    # the data over to the new column
    op.drop_column('battle_teams', 'won')

    op.alter_column('battle_trainers', 'trainer_id', nullable=True,
        existing_type=sa.Integer)

    op.add_column('battles', sa.Column('length', sa.Unicode(), nullable=True))

    # Make battle names non-unique
    op.drop_constraint('battles_name_key', 'battles')

def downgrade():
    # Untouched autogenerated commands; they should work
    op.create_unique_constraint('battles_name_key', 'battles', ['name'])
    op.drop_column('battles', 'length')
    op.alter_column('battle_trainers', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('battle_teams', sa.Column('won', sa.BOOLEAN(), nullable=False))
    op.drop_column('battle_teams', 'outcome')
    op.alter_column('battle_pokemon', 'gender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('battle_pokemon', 'kos')
    op.drop_table('battle_lengths')
    op.drop_table('battle_outcomes')
