"""Add a couple of history columns Pokémon.

Revision ID: 4ef0dceb2d3
Revises: 27f4a73abe9
Create Date: 2015-01-31 22:56:31.936530

"""

# revision identifiers, used by Alembic.
revision = '4ef0dceb2d3'
down_revision = '27f4a73abe9'

import datetime

from alembic import op
import sqlalchemy as sa

pokemon = sa.sql.table(
    'pokemon',
    sa.Column('id', sa.Integer),
    sa.Column('birthday', sa.Date),
    sa.Column('was_from_hack', sa.Boolean)
)

def upgrade():
    op.add_column('pokemon', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('pokemon', sa.Column('was_from_hack', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('pokemon', 'was_from_hack', server_default=None)

    op.execute(
        pokemon.update()
        .values({'birthday': datetime.date.today()})
    )

    op.execute(
        pokemon.update()
        .where(pokemon.c.id < 0)
        .values({'was_from_hack': True})
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'was_from_hack')
    op.drop_column('pokemon', 'birthday')
    ### end Alembic commands ###
