"""Add Pokémon form name columns.

Revision ID: 7e21fe9064
Revises: 2b1cbfad9c4
Create Date: 2013-12-21 20:04:56.544268

"""

# revision identifiers, used by Alembic.
revision = '7e21fe9064'
down_revision = '2b1cbfad9c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon_forms', sa.Column('form_name', sa.Unicode(), nullable=True))
    op.add_column('pokemon_forms', sa.Column('full_name', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon_forms', 'full_name')
    op.drop_column('pokemon_forms', 'form_name')
    ### end Alembic commands ###
