"""Add Pokémon order columns.

Revision ID: d68f595546
Revises: 19984d283c2
Create Date: 2013-12-22 08:59:35.290028

"""

# revision identifiers, used by Alembic.
revision = 'd68f595546'
down_revision = '19984d283c2'

from alembic import op
import sqlalchemy as sa

pokemon_forms = sa.sql.table('pokemon_forms',
    sa.Column('id', sa.Integer),
    sa.Column('order', sa.Integer)
)

pokemon_species = sa.sql.table('pokemon_species',
    sa.Column('id', sa.Integer),
    sa.Column('order', sa.Integer)
)

def upgrade():
    op.add_column('pokemon_forms', sa.Column('order', sa.Integer()))
    op.add_column('pokemon_species', sa.Column('order', sa.Integer()))

    op.execute(pokemon_forms.update().values({'order': pokemon_forms.c.id}))
    op.execute(pokemon_species.update().values({'order': pokemon_species.c.id}))

    op.alter_column('pokemon_forms', 'order', nullable=False)
    op.alter_column('pokemon_species', 'order', nullable=False)

    op.create_unique_constraint('pokemon_forms_order_key', 'pokemon_forms',
        ['order'])
    op.create_unique_constraint('pokemon_species_order_key', 'pokemon_species',
        ['order'])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon_species', 'order')
    op.drop_column('pokemon_forms', 'order')
    ### end Alembic commands ###
